name: momentum
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  http: ^1.4.0
  get: ^4.6.5
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  path_provider: ^2.0.11
  dio_cookie_manager: ^3.2.0
  flutter_secure_storage: ^9.2.4 
  flutter_chat_ui: ^1.6.15
  uuid: ^4.0.0
  shared_preferences: ^2.2.2
  uni_links: ^0.5.1
  url_launcher: ^6.1.7
  flutter_web_auth: ^0.6.0
  table_calendar: ^3.0.9 
  intl: ^0.19.0
  syncfusion_flutter_calendar: ^28.2.6
  geolocator: ^14.0.0
  flutter_map: ^8.0.0
  flutter_map_marker_popup: ^8.0.1
  flutter_map_location_marker: ^10.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
