name: momentum
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  http: ^0.13.4
  get: ^4.6.5
  flutter:
    sdk: flutter
  dio: ^5.0.0
  path_provider: ^2.0.11
  dio_cookie_manager: ^3.2.0
  flutter_secure_storage: ^9.2.4 
  shared_preferences: ^2.2.2
  geolocator: ^10.0.0
  flutter_map: ^4.0.0
  flutter_map_marker_popup: ^4.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
