// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWjGCiqwdgVYG86f6GADI2GJr8tXeuweM',
    appId: '1:1089764157877:web:d2ba3b6a4bf41408ca91fc',
    messagingSenderId: '1089764157877',
    projectId: 'momentumapp-73123',
    authDomain: 'momentumapp-73123.firebaseapp.com',
    storageBucket: 'momentumapp-73123.firebasestorage.app',
    measurementId: 'G-RN0MVYSP02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBu0qA-Y-y5TC2EfacHeeBHeb792sy3XA',
    appId: '1:1089764157877:android:d6d9eb1881e6b681ca91fc',
    messagingSenderId: '1089764157877',
    projectId: 'momentumapp-73123',
    storageBucket: 'momentumapp-73123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPAxFgGVLXAPOqSWSzaXiqlrjNKotvQEM',
    appId: '1:1089764157877:ios:f86352181a223f4aca91fc',
    messagingSenderId: '1089764157877',
    projectId: 'momentumapp-73123',
    storageBucket: 'momentumapp-73123.firebasestorage.app',
    iosBundleId: 'com.example.momentum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPAxFgGVLXAPOqSWSzaXiqlrjNKotvQEM',
    appId: '1:1089764157877:ios:f86352181a223f4aca91fc',
    messagingSenderId: '1089764157877',
    projectId: 'momentumapp-73123',
    storageBucket: 'momentumapp-73123.firebasestorage.app',
    iosBundleId: 'com.example.momentum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWjGCiqwdgVYG86f6GADI2GJr8tXeuweM',
    appId: '1:1089764157877:web:d960963b9bbca94eca91fc',
    messagingSenderId: '1089764157877',
    projectId: 'momentumapp-73123',
    authDomain: 'momentumapp-73123.firebaseapp.com',
    storageBucket: 'momentumapp-73123.firebasestorage.app',
    measurementId: 'G-0WFT8DVXZG',
  );
}
